theme: jekyll-theme-minimal
title: OMNI/RÉUNIS Course on One Health Modelling for Emerging Infectious Diseases
description: Julien Arino - Course material (slides and code).
show_downloads: true
logo: https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Schistosoma_20041-300.jpg/1280px-Schistosoma_20041-300.jpg
google_analytics: UA-1943806-8
plugins:
  - jekyll-sitemap
